[package]
name = "roko-http"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen-futures = "0.4.37"
roko-macro = { path = "../roko-macro" }
reqwest = "0.11.18"
